/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.tunipharma.gui;

import edu.tunipharma.gui.PharmacienView;

/**
 *
 * @author azerty
 */
public class AjouterPharmacien extends javax.swing.JFrame {

    /**
     * Creates new form AjouterPharmacien
     */
    public AjouterPharmacien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();
        Ajouter1 = new javax.swing.JButton();
        Ajouter2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAjoutPharmacien = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ajouter.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Ajouter.setForeground(new java.awt.Color(0, 102, 51));
        Ajouter.setText("Accepter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        Ajouter1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Ajouter1.setForeground(new java.awt.Color(0, 102, 51));
        Ajouter1.setText("Reffuser");
        Ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter1ActionPerformed(evt);
            }
        });

        Ajouter2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Ajouter2.setForeground(new java.awt.Color(0, 102, 51));
        Ajouter2.setText("Retour");
        Ajouter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter2ActionPerformed(evt);
            }
        });

        TableAjoutPharmacien.setModel(new MyTableModelPhrn());
        jScrollPane1.setViewportView(TableAjoutPharmacien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ajouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ajouter1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ajouter2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter2)
                    .addComponent(Ajouter)
                    .addComponent(Ajouter1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        // TODO add your handling code here:
//        if(!tbIdPh.getText().equals("") && !tbPrixS.getText().equals(""))
//        {
//            ServiceDAO sdao= new ServiceDAO();
//            Service ss= new Service();
//            ss.setId_ph(Integer.parseInt(tbIdPh.getText()));
//            //mm.setPrix(Integer.parseInt(spPrix.getValue()));
//            // mm.setPrix(Integer.parseInt(tbPrix.getText()));
//            ss.setPrix_sr(Float.parseFloat(tbPrixS.getText()));
//            ss.setType_sr((String) cbTypeS.getSelectedItem());
//            JOptionPane.showMessageDialog(null,"Service ajoutée !");
//
//            sdao.insertService(ss);
//
//            new ServiceView().setVisible(true);
//            this.dispose();
//        }else{
//            JOptionPane.showMessageDialog(null,"Tout les champs sont obligatoires !");
//
//        }
    }//GEN-LAST:event_AjouterActionPerformed

    private void Ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ajouter1ActionPerformed

    private void Ajouter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter2ActionPerformed
        // TODO add your handling code here:
        new PharmacienView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ajouter2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterPharmacien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterPharmacien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterPharmacien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterPharmacien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterPharmacien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Ajouter1;
    private javax.swing.JButton Ajouter2;
    private javax.swing.JTable TableAjoutPharmacien;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
