/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tunipharma.gui;

import edu.tunipharma.dao.ClientDAO;
import edu.tunipharma.entities.Client;
import java.util.Date;

/**
 *
 * @author Mohamed
 */
public class Details_Client extends javax.swing.JFrame {
    
    
    ClientDAO cldao =new ClientDAO();
    int id=0;
    

    /**
     * Creates new form Details_Client
     */
    public Details_Client(int id) {
        initComponents();
        
        Client cl=new Client();
        int idClient=id;
        cl=cldao.findClientById(id);
        tf_nom.setText(cl.getNom());
        tf_prenom.setText(cl.getPrenom());
        tf_sexe.setText(cl.getSexe());
        tf_date_naissance.setText(cl.getDate_Naissance());
        tf_adresse_mail.setText(cl.getAdresse_mail());
        tf_gouvernaurat.setText(cl.getGouvernaurat());
        tf_ville.setText(cl.getVille());
        tf_adresse.setText(cl.getAdresse());
        
        
        
        
    }

    private Details_Client() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lb_nom = new javax.swing.JLabel();
        btn_retour = new javax.swing.JButton();
        lb_prenom = new javax.swing.JLabel();
        lb_sexe = new javax.swing.JLabel();
        lb_date_naissance = new javax.swing.JLabel();
        lb_adresse_mail = new javax.swing.JLabel();
        lb_gouvernaurat = new javax.swing.JLabel();
        lb_ville = new javax.swing.JLabel();
        lb_adresse = new javax.swing.JLabel();
        tf_nom = new javax.swing.JTextField();
        tf_ville = new javax.swing.JTextField();
        tf_adresse = new javax.swing.JTextField();
        tf_adresse_mail = new javax.swing.JTextField();
        tf_gouvernaurat = new javax.swing.JTextField();
        tf_sexe = new javax.swing.JTextField();
        tf_date_naissance = new javax.swing.JTextField();
        tf_prenom = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_nom.setText("Nom:");

        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        lb_prenom.setText("Prenom:");

        lb_sexe.setText("Sexe:");

        lb_date_naissance.setText("Date_Naissance:");

        lb_adresse_mail.setText("Adresse_mail:");

        lb_gouvernaurat.setText("Gouvernaurat:");

        lb_ville.setText("Ville:");

        lb_adresse.setText("Adresse:");

        tf_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomActionPerformed(evt);
            }
        });

        tf_ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_villeActionPerformed(evt);
            }
        });

        tf_adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_adresseActionPerformed(evt);
            }
        });

        tf_date_naissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_date_naissanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_adresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_sexe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_prenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_adresse_mail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_date_naissance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_ville, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lb_gouvernaurat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tf_gouvernaurat)
                    .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_prenom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_sexe, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_date_naissance, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_adresse_mail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_ville, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_adresse, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nom)
                    .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_prenom)
                    .addComponent(tf_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_sexe)
                    .addComponent(tf_sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_date_naissance)
                    .addComponent(tf_date_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_adresse_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_adresse_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gouvernaurat)
                    .addComponent(tf_gouvernaurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ville)
                    .addComponent(tf_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_adresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_retour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_date_naissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_date_naissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_date_naissanceActionPerformed

    private void tf_villeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_villeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_villeActionPerformed

    private void tf_adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_adresseActionPerformed

    private void tf_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
       
    Frame_Affichage z1 =new Frame_Affichage();
    z1.setVisible(true);
    dispose();
        
    }//GEN-LAST:event_btn_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details_Client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_retour;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_adresse;
    private javax.swing.JLabel lb_adresse_mail;
    private javax.swing.JLabel lb_date_naissance;
    private javax.swing.JLabel lb_gouvernaurat;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_prenom;
    private javax.swing.JLabel lb_sexe;
    private javax.swing.JLabel lb_ville;
    private javax.swing.JTextField tf_adresse;
    private javax.swing.JTextField tf_adresse_mail;
    private javax.swing.JTextField tf_date_naissance;
    private javax.swing.JTextField tf_gouvernaurat;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_prenom;
    private javax.swing.JTextField tf_sexe;
    private javax.swing.JTextField tf_ville;
    // End of variables declaration//GEN-END:variables
}
