/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.tunipharma.gui;

import edu.tunipharma.dao.PharmacieDAO;
import edu.tunipharma.entities.Pharmacie;
import javax.swing.JOptionPane;

/**
 *
 * @author azerty
 */
public class ModifierPharmacie extends javax.swing.JFrame {

    PharmacieDAO phdao = new PharmacieDAO();
    /**
     * Creates new form ModifierPharmacie
     */
    public ModifierPharmacie() {
        initComponents();
    }
     String garde ="";
    public ModifierPharmacie(int id) {
        initComponents();
        
       Pharmacie p= new Pharmacie();
        int idPharmacie=id;
       p= phdao.findPharmacieById(id);
       tbIdPh.enable(false);
       tbIdPh.setText(Integer.toString(p.getId_ph()));
       tbNomph.setText(p.getNom_ph());
       tbTelPh.setText(Integer.toString(p.getTel()));
       tbFaxPh.setText(Integer.toString(p.getFax()));
       tbAddPh.setText(p.getAdresse());
      
        if(brOui.isSelected())
            garde=brOui.getText();
        if(brNon.isSelected())
            garde=brNon.getText();
       if(p.getType().equalsIgnoreCase("jour"))
       {
           cbTypePh.setSelectedIndex(0);
       }else
       {
           cbTypePh.setSelectedIndex(1);
       }
       
       if(p.getGouvernorat().equalsIgnoreCase("Sfax"))
       {
           cbGvt.setSelectedIndex(0);
       }
       else if(p.getGouvernorat().equalsIgnoreCase("Ariana"))
       {
           cbGvt.setSelectedIndex(1);
       }
       else if(p.getGouvernorat().equalsIgnoreCase("Monastir"))
       {
           cbGvt.setSelectedIndex(2);
       }
       else if(p.getGouvernorat().equalsIgnoreCase("Tunis"))
       {
           cbGvt.setSelectedIndex(3);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Sousse"))
       {
           cbGvt.setSelectedIndex(4);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Ben Arous"))
       {
           cbGvt.setSelectedIndex(5);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Bizerte"))
       {
           cbGvt.setSelectedIndex(6);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Béja"))
       {
           cbGvt.setSelectedIndex(7);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Gabès"))
       {
           cbGvt.setSelectedIndex(8);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Gafsa"))
       {
           cbGvt.setSelectedIndex(9);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Jendouba"))
       {
           cbGvt.setSelectedIndex(10);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Kairouan"))
       {
           cbGvt.setSelectedIndex(11);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Kasserine"))
       {
           cbGvt.setSelectedIndex(12);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Kébeli"))
       {
           cbGvt.setSelectedIndex(13);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("La Manouba"))
       {
           cbGvt.setSelectedIndex(14);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("La Kef"))
       {
           cbGvt.setSelectedIndex(15);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Mahdia"))
       {
           cbGvt.setSelectedIndex(16);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Médenine"))
       {
           cbGvt.setSelectedIndex(17);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Nabeul"))
       {
           cbGvt.setSelectedIndex(18);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Sidi Bouzid"))
       {
           cbGvt.setSelectedIndex(19);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Siliana"))
       {
           cbGvt.setSelectedIndex(20);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Tataouine"))
       {
           cbGvt.setSelectedIndex(21);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Tozeur"))
       {
           cbGvt.setSelectedIndex(22);
       }
         else if(p.getGouvernorat().equalsIgnoreCase("Zaghouan"))
       {
           cbGvt.setSelectedIndex(23);
       }
         
               
    
       
       
       
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbIdPh = new javax.swing.JTextField();
        tbTelPh = new javax.swing.JTextField();
        tbFaxPh = new javax.swing.JTextField();
        cbTypePh = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAddPh = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbNomph = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbGvt = new javax.swing.JComboBox();
        brOui = new javax.swing.JRadioButton();
        brNon = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Adresse :");

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Id :");

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Type :");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setText("Fax :");

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("Telephone:");

        tbIdPh.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        tbTelPh.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        tbFaxPh.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        cbTypePh.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        cbTypePh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jour", "Nuit" }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 51));
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 51));
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbAddPh.setColumns(20);
        tbAddPh.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        tbAddPh.setRows(5);
        jScrollPane1.setViewportView(tbAddPh);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("Garde :");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText("Modifier Pharmacie");

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("Nom Pharmacie :");

        tbNomph.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setText("Gouvernorat :");

        cbGvt.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        cbGvt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sfax", "Ariana", "Monastir", "Tunis", "Sousse", "Ben Arous", "Bizerte", "Béja", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "La Manouba", "Le Kef", "Mahdia", "Médenine", "Nabeul", "Sidi Bouzid", "Siliana", "Tataouine", "Tozeur", "Zaghouan", " " }));

        buttonGroup1.add(brOui);
        brOui.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        brOui.setText("Oui");

        buttonGroup1.add(brNon);
        brNon.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        brNon.setText("Non");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tbTelPh, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbNomph, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addComponent(tbIdPh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbFaxPh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbGvt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbTypePh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(brOui)
                                .addGap(18, 18, 18)
                                .addComponent(brNon))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbIdPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tbNomph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbTelPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbFaxPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brOui)
                        .addComponent(brNon)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTypePh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbGvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        Pharmacie pp= new Pharmacie();
        
        pp.setAdresse(tbAddPh.getText());
        pp.setNom_ph(tbNomph.getText());
        pp.setFax(Integer.parseInt(tbFaxPh.getText()));
        pp.setTel(Integer.parseInt(tbTelPh.getText()));
        pp.setId_ph(Integer.parseInt(tbIdPh.getText()));
        pp.setType((String) cbTypePh.getSelectedItem());
        pp.setGouvernorat((String) cbGvt.getSelectedItem());
        if(brOui.isSelected())
            garde=brOui.getText();
        if(brNon.isSelected())
            garde=brNon.getText();
        pp.setGarde(garde);
       
        phdao.updatePharmacie(pp);
         JOptionPane.showMessageDialog(null,"Pharmacie modifiee !");
               new pharmacieView().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            new pharmacieView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierPharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton brNon;
    private javax.swing.JRadioButton brOui;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbGvt;
    private javax.swing.JComboBox cbTypePh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tbAddPh;
    private javax.swing.JTextField tbFaxPh;
    private javax.swing.JTextField tbIdPh;
    private javax.swing.JTextField tbNomph;
    private javax.swing.JTextField tbTelPh;
    // End of variables declaration//GEN-END:variables
}
