/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.tunipharma.gui;

import edu.tunipharma.dao.PharmacieDAO;
import edu.tunipharma.entities.Pharmacie;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azerty
 */
public class pharmacieView extends javax.swing.JFrame {

    PharmacieDAO u = new PharmacieDAO();
    int b;

    /**
     * Creates new form pharmacieView
     */
    public pharmacieView() {
        initComponents();
        MyTableModel affPhar =new MyTableModel();
        tablePhar.setModel(affPhar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhar = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cbGvt = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbtype = new javax.swing.JComboBox();
        btnAjouterSrv = new javax.swing.JButton();
        btnAjouterMdc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface Pharmacie");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tablePhar.setAutoCreateRowSorter(true);
        tablePhar.setBackground(new java.awt.Color(0, 102, 51));
        tablePhar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        tablePhar.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        tablePhar.setForeground(new java.awt.Color(102, 255, 102));
        tablePhar.setModel(new MyTableModelPharmacieFind());
        tablePhar.setDragEnabled(true);
        tablePhar.setGridColor(new java.awt.Color(51, 102, 0));
        tablePhar.setInheritsPopupMenu(true);
        tablePhar.setSelectionBackground(new java.awt.Color(51, 102, 0));
        jScrollPane1.setViewportView(tablePhar);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 51));
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnModifier.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(0, 102, 51));
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 51));
        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Listes des Pharmacies");

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 51));
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbGvt.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        cbGvt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tout", "Sfax", "Ariana", "Monastir", "Tunis", "Sousse", "Ben Arous", "Bizerte", "Béja", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "La Manouba", "Le Kef", "Mahdia", "Médenine", "Nabeul", "Sidi Bouzid", "Siliana", "Tataouine", "Tozeur", "Zaghouan", " " }));
        cbGvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGvtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Rechercher par Gouvernements :");

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Rechercher par Type :");

        cbtype.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        cbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tout", "Jour", "Nuit" }));
        cbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtypeActionPerformed(evt);
            }
        });

        btnAjouterSrv.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnAjouterSrv.setForeground(new java.awt.Color(0, 102, 51));
        btnAjouterSrv.setText("Ajouter Service");
        btnAjouterSrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterSrvActionPerformed(evt);
            }
        });

        btnAjouterMdc.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnAjouterMdc.setForeground(new java.awt.Color(0, 102, 51));
        btnAjouterMdc.setText("Ajouter Medicament");
        btnAjouterMdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterMdcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGvt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnAjouterMdc, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(btnAjouterSrv, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnModifier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterSrv)
                    .addComponent(btnAjouterMdc))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (tablePhar.getSelectedRow() != -1) {
            int id = (Integer) tablePhar.getValueAt(tablePhar.getSelectedRow(), 0);
             b=JOptionPane.showConfirmDialog(null,"étes vous sur?" , "message", JOptionPane.YES_NO_OPTION, 1);
             if(b == JOptionPane.OK_OPTION){
            u.deletePharmacie(id);
            MyTableModel ii = new MyTableModel();
            tablePhar.setModel(ii);
             }
        } else {
            JOptionPane.showMessageDialog(null, "Invalide choice");
        }

//                    if(tablePhar.getSelectedRow()>=0 && tablePhar.getSelectedColumn()==0){
//                        
//                        
//                        b=JOptionPane.showConfirmDialog(null,"étes vous sur?" , "message", JOptionPane.YES_NO_OPTION, 1);
//if(b == JOptionPane.OK_OPTION)
//{
//        
//                  int selectedRow = tablePhar.getSelectedRow();  
//                   int selectedColumn = tablePhar.getSelectedColumn();  
//                 Object selectedCellValue=tablePhar.getValueAt(selectedRow, selectedColumn); 
//               
//                u.deletePharmacie((int)selectedCellValue);
//                MyTableModel ii= new MyTableModel();
//                tablePhar.setModel(ii);
//                    }}else {

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
          int id = (Integer) tablePhar.getValueAt(tablePhar.getSelectedRow(), 0); 
//        int selectedRow = tablePhar.getSelectedRow();
//        int selectedColumn = tablePhar.getSelectedColumn();
//        Object selectedCellValue = tablePhar.getValueAt(selectedRow, selectedColumn);
//
//        new ModifierPharmacie((int) selectedCellValue).setVisible(true);
          new ModifierPharmacie(id).setVisible(true);
          this.dispose();


    }//GEN-LAST:event_btnModifierActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new AjouterPharmacie().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new MenuView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbGvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGvtActionPerformed
        // TODO add your handling code here:
        String ll=(String)cbGvt.getSelectedItem();
        System.out.println(ll);
        if (cbGvt.getSelectedIndex()==0){
        MyTableModel affphar = new MyTableModel();
        tablePhar.setModel(affphar);
        }else{
        
         MyTableModelPharmacieFind.ok=ll;
        MyTableModelPharmacieFind k= new MyTableModelPharmacieFind();
         tablePhar.setModel(k);
        }
        
        
    }//GEN-LAST:event_cbGvtActionPerformed

    private void cbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtypeActionPerformed
        // TODO add your handling code here:
         String ll=(String)cbtype.getSelectedItem();
        System.out.println(ll);
        if (cbtype.getSelectedIndex()==0){
        MyTableModel affphar = new MyTableModel();
        tablePhar.setModel(affphar);
        }else{
        
         MyTableModelTypePharmacie.okok=ll;
        MyTableModelTypePharmacie k= new MyTableModelTypePharmacie();
         tablePhar.setModel(k);
        }
    }//GEN-LAST:event_cbtypeActionPerformed

    private void btnAjouterSrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterSrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterSrvActionPerformed

    private void btnAjouterMdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterMdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterMdcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharmacieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharmacieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharmacieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharmacieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pharmacieView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterMdc;
    private javax.swing.JButton btnAjouterSrv;
    private javax.swing.JButton btnModifier;
    private javax.swing.JComboBox cbGvt;
    private javax.swing.JComboBox cbtype;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePhar;
    // End of variables declaration//GEN-END:variables
}
